### ISSUE TITLE
Update configure scripts

### ISSUE THREAD

**Issue by giordano** [coin-or-tools/ThirdParty-Blas#1]
Could you please update the `configure` script and all the helper scripts?  For example, `config.guess` and `config.sub` are 13-year old, it's impossible with the scripts shipped by this package to build for Musl-based platforms, or the shared library for FreeBSD and PowerPC.  It's also impossible to run `autoreconf` because this package isn't self-contained and it doesn't ship the definitions of the M4 macros used in `configure.ac`:
```
$ autoreconf -vi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf
configure.ac:33: error: possibly undefined macro: AC_COIN_PROJECTDIR_INIT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:47: error: possibly undefined macro: AC_COIN_DEBUG_COMPILE
configure.ac:50: error: possibly undefined macro: AC_COIN_PROG_F77
configure.ac:53: error: possibly undefined macro: AC_COIN_F77_WRAPPERS
configure.ac:60: error: possibly undefined macro: AC_COIN_HAS_PKGCONFIG
configure.ac:63: error: possibly undefined macro: AC_COIN_INIT_AUTO_TOOLS
configure.ac:67: error: possibly undefined macro: AC_COIN_FINALIZE
```

**Comment by svigerske** [comment]
There is no intention to keep this project alive. In the near future, COIN-OR projects will not depend on this anymore (and currently it's also only optional) and this project will then be archived.

**Comment by giordano** [comment]
Can you please at least tell me where the macros come from so that I can `autoreconf` locally?

**Comment by svigerske** [comment]
https://github.com/coin-or-tools/BuildTools/tree/stable/0.8

**Comment by giordano** [comment]
Thanks!
